language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t jbunyadzade/docker-react -f Dockerfile.dev .

script:
    - docker run jbunyadzade/docker-react npm run test -- --coverage
